# Use postgres/example user/password credentials
version: '3.1'

services:

  react:
    build:
      context: ./app
    ports: 
      - 4000:4000
    volumes:
      - ./app:/app

  go:
    build:
      context: ./go
    ports: 
      - 9000:9000
    volumes:
      - ./go:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    volumes:
    - ./database:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    volumes:
      - ./go/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000




# volumes:
#   - userdata